apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-mlf0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-mlf0
    app.kubernetes.io/part-of: devfile-sample-code-with-quarkus
  name: devfile-sample-code-with-quarkus-mlf0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-mlf0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-mlf0
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/beaumorley-tenant/devfile-sample-code-with-quarkus/devfile-sample-code-with-quarkus-mlf0@sha256:1675b0b18a8e5cfb7d83f74372e147a36b0eb7ac4175b5760e0422cbb4d4e2d8
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
